name: CI

on:
  push:
    branches:
      - 'main'

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Chez Scheme
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y chezscheme

    - name: Set up Chez Scheme
      if: runner.os == 'macOS'
      run: |
        brew install chezscheme

    ## using `apt-get install -y z3` installs an older version of Z3
    ## and they have differnt text layout for `(get-model)`
    - name: Set up Z3
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        sudo apt-get install -y unzip
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.13.0/z3_solver-4.13.0.0-py2.py3-none-manylinux2014_x86_64.whl
        unzip z3_solver-4.13.0.0-py2.py3-none-manylinux2014_x86_64.whl
        echo "$PWD/z3_solver-4.13.0.0.data/data/bin" >> $GITHUB_PATH

    - name: Set up Z3
      if: runner.os == 'macOS'
      run: |
        brew install z3

    - name: Set up CVC5
      if: runner.os == 'Linux'
      run: |
        wget https://github.com/cvc5/cvc5/releases/download/cvc5-1.1.2/cvc5-Linux-static.zip
        unzip cvc5-Linux-static.zip
        echo "$PWD/cvc5-Linux-static/bin" >> $GITHUB_PATH

    # macos latests by default is arm-based
    - name: Set up CVC5
      if: runner.os == 'macOS'
      run: |
        wget https://github.com/cvc5/cvc5/releases/download/cvc5-1.1.2/cvc5-macOS-arm64-static.zip
        unzip cvc5-macOS-arm64-static.zip
        echo "$PWD/cvc5-macOS-arm64-static/bin" >> $GITHUB_PATH

    - name: Verify installations
      if: runner.os == 'macOS'
      run: |
        chez --version
        z3 --version
        cvc5 --version
    
    - name: Verify installations
      if: runner.os == 'Linux'
      run: |
        scheme --version
        cvc5 --version
        z3 --version

    - name: Run CLPSMT tests on z3
      if: runner.os == 'macOS'
      run: |
        time chez --script tests/z3-test.scm
    
    - name: Run CLPSMT tests on z3
      if: runner.os == 'Linux'
      run: |
        time scheme --script tests/z3-test.scm

    - name: Run CLPSMT tests on cvc5
      if: runner.os == 'macOS'
      run: |
        time chez --script tests/cvc5-test.scm
      
    - name: Run CLPSMT tests on cvc5
      if: runner.os == 'Linux'
      run: |
        time scheme --script tests/cvc5-test.scm   

    - name: Run Hoare Logic on z3
      if: runner.os == 'macOS'
      run: |
        time chez --script test-implieso.scm
        time chez --script test-normo.scm
        time chez --script test-syntax.scm 
        time chez --script test-substo.scm
        time chez --script test-hoare.scm
