name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Chez Scheme
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y chezscheme

    - name: Set up Chez Scheme
      if: runner.os == 'macOS'
      run: |
        brew install chezscheme

    - name: Set up Z3
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y z3

    - name: Set up Z3
      if: runner.os == 'macOS'
      run: |
        brew install z3

    - name: Set up CVC5
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git
        git clone https://github.com/arminbiere/cadical.git
        cd cadical
        ./configure && make
        git clone https://github.com/cvc5/cvc5.git
        cd cvc5
        ./configure.sh
            # use --prefix to specify an install prefix (default: /usr/local)
            # use --name=<PATH> for custom build directory
            # use --auto-download to download and build missing, required or
            #   enabled, dependencies
        cd ./build       # default is ./build
        make             # use -jN for parallel build with N threads
        make check       # to run default set of tests
        make install     # to install into the prefix specified above

    - name: Set up CVC5
      if: runner.os == 'macOS'
      run: |
        brew install cvc5/homebrew-cvc5/cvc5

    - name: Verify installations
      run: |
        chez --version
        z3 --version
        cvc5 --version
